apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: www-aloyoga-rocks-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - www.aloyoga.rocks
        - aloyoga.rocks
      secretName: www-aloyoga-rocks-tls
  rules:
    - host: www.aloyoga.rocks
      http:
        paths:
          - backend:
              serviceName: aloyoga-rocks-deeplink
              servicePort: 80
    - host: aloyoga.rocks
      http:
        paths:
          - backend:
              serviceName: aloyoga-rocks-deeplink
              servicePort: 80
