apiVersion: v1
kind: Service
metadata:
  name: aloyoga-rocks-deeplink
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: aloyoga-rocks-deeplink
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aloyoga-rocks-deeplink
spec:
  selector:
    matchLabels:
      app: aloyoga-rocks-deeplink
  replicas: 1
  template:
    metadata:
      labels:
        app: aloyoga-rocks-deeplink
    spec:
      containers:
      - name: aloyoga-rocks-deeplink
        image: aloyoga/app20-universal-link:7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
